// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFlcgnRCa-qS7_CjBvEgoAtiNO2USNoBA',
    appId: '1:93097008048:web:0f1a8474555be068d49475',
    messagingSenderId: '93097008048',
    projectId: 'project0000-ec01e',
    authDomain: 'project0000-ec01e.firebaseapp.com',
    databaseURL:
        'https://project0000-ec01e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project0000-ec01e.firebasestorage.app',
    measurementId: 'G-0DKS7JJL5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_klPq9yspgkyoLD1rs-w9OmIJExx4MBw',
    appId: '1:93097008048:android:0ccdec23053fc259d49475',
    messagingSenderId: '93097008048',
    projectId: 'project0000-ec01e',
    databaseURL:
        'https://project0000-ec01e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project0000-ec01e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-OYxr_0iywf5G9uWpPG32TWva416WcnY',
    appId: '1:93097008048:ios:7cc378f1a02877ffd49475',
    messagingSenderId: '93097008048',
    projectId: 'project0000-ec01e',
    databaseURL:
        'https://project0000-ec01e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project0000-ec01e.firebasestorage.app',
    iosClientId:
        '93097008048-m72v2b01l0kpidn3nkah94mt7om8ub3g.apps.googleusercontent.com',
    iosBundleId: 'com.warmhandongne.msg',
  );
}
